# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fish' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fish
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~> 1.0.2'
	pod 'ReactiveObjC', '~> 3.0.0'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'YYKit', '~> 1.0.9'
    pod 'YTKNetwork'
end
