# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fish' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fish
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~> 1.0.2'
	pod 'ReactiveObjC', '~> 3.0.0'
	pod 'YYKit', '~> 1.0.9'
    pod 'YTKNetwork'
    pod 'PNChart'
     pod 'DZNEmptyDataSet', '~> 1.8.1'
     pod 'RongCloudIMKit', '~> 2.7.3.1'
     pod 'FSCalendar'
     pod 'JPush', '3.0.2'
     pod 'SDCycleScrollView', '~> 1.66'
     pod 'MJRefresh', '~> 3.1.12'
     pod 'AMap3DMap'
     pod 'IQKeyboardManager', '~> 5.0.6'
     pod 'MBProgressHUD+JDragon'
     pod 'PGDatePicker', '>= 1.4.5'
end
